[workspace]
value_file = "signac_statepoint.json"

[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

[default.action.submit_options.borah]
output_file_path="out"
output_file_name="{action_name}-%j.out"
setup = """
  source ~/miniconda3/etc/profile.d/conda.sh
  conda activate ellipsoids
"""
custom = [
  "--mail-type=END,FAIL",
  "--mail-user=cooperpiehl@boisestate.edu",
  "--gres=gpu:1",
  "--partition=gpu-l40",
  "--error=errors/%j.err"
]

[[action]]
name = "run_sim"
products = ["trajectory.gsd"]

[action.resources]
processes.per_submission = 1
threads_per_process = 8
gpus_per_process = 1

[[action]]
name = "process_logs"
products = ["ovito-trajectory.gsd"]
previous_actions = ["run_sim"]


